# Generated by Django 4.2.7 on 2025-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
        migrations.AddField(
            model_name='queue',
            name='patient_name',
            field=models.CharField(default='Walk-in', max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Add to queue'),
        ),
    ]
