# Generated by Django 4.2.7 on 2025-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_remove_queue_created_at_remove_queue_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.CharField(max_length=36, unique=True, verbose_name='Add to queue'),
        ),
    ]
