# Generated by Django 4.2.7 on 2025-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
