# Generated by Django 4.2.7 on 2025-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='bed',
            name='available',
            field=models.PositiveIntegerField(default=0, help_text='Number of available beds'),
        ),
        migrations.AddField(
            model_name='bed',
            name='occupied',
            field=models.PositiveIntegerField(default=0, help_text='Number of occupied beds'),
        ),
    ]
