# Generated by Django 5.2.6 on 2025-11-25 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_create_bedhold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedhold',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
