# Generated by Django 4.2.7 on 2025-11-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_alter_bedhold_created_at'),
        ('beds', '0005_bedhold_bed'),
    ]

    operations = [
    ]
